Revert "refactor: Use `JsonBone` for computed JSON"
This reverts commit 8a06f21ddc5fb58ab9d33b96dac8b6d1765d6f2f.

Getting error
```
    assert self.renderPreparation is None, "Cannot modify values while rendering"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot modify values while rendering
```